name: VyOS 1.3.x fullconenat kernel Build and Release
permissions:
  contents: write
on:
  push:
    tags:
      - "*"
  
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      # For VyOS 1.2 (crux) use vyos/vyos-build:crux
      # For VyOS 1.3 (equuleus) use vyos/vyos-build:equuleus
      # For our VyOS rolling release you should use vyos/vyos-build which will always refer to the latest image.
      # Ref: https://docs.vyos.io/en/latest/contributing/build-vyos.html#build
      image: vyos/vyos-build:equuleus
      env:
        TZ: Asia/Shanghai
      options: --privileged
      
    steps:

    - name: git clone vyos-kernel-build
      run: |
        set -eux
        sudo apt-get --install-recommends install pciutils yasm
         git clone -b dev  https://github.com/debiansid/vyos-kernel-lts-build linux-kernel
         
         
    - name: make kernel deb
    #  working-directory: linux-kernel
      run: |
        set -eux
        pwd

        cd linux-kernel
        wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.4.240.tar.xz
        tar xf linux-5.4.240.tar.xz
        ln -s linux-5.4.240 linux
        ./build-kernel.sh
        rm *dev*.deb
    - name: make intel-qat deb
      run: |
        set -eux
        pwd
        cd linux-kernel
        ./build-intel-qat.sh
    - name: make wirgeguard deb
      run: |
        set -eux
        pwd
        cd linux-kernel
        git clone https://salsa.debian.org/debian/wireguard-linux-compat.git
        cd wireguard-linux-compat
        git checkout debian/1.0.20210606-1
        cd ../
        ./build-wireguard-modules.sh
    - name: make Accel-PPP deb
      run: |
        set -eux
        pwd
        git clone https://github.com/accel-ppp/accel-ppp.git
        ./build-accel-ppp.sh
    - name: ls
      run: |
        set -eux

        pwd
        ls -lah linux-kernel

    - name: Upload release
      uses: softprops/action-gh-release@v0.1.15
      with:
          tag_name: ${{ github.ref_name }}
          files: |
               linux-kernel/linux*.deb
               linux-kernel/vyos-*.deb
               linux-kernel/accel-ppp*.deb
               linux-kernel/wireguard-*.deb
          draft: true
          prerelease: true
          
